mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-super-type: java.lang.Object
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    aggressive-lazy-loading: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: none
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    multiple-result-sets-enabled: false
  global-config:
    db-config:
      table-underline: false
      id-type: auto
      capital-mode: false
      logic-not-delete-value: 0
      logic-delete-value: 1

spring:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    druid:
      username: yyh
      password: 1234qwerQWER
      url: jdbc:mysql://192.168.0.232:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: 6379
    password: 1234qwerQWER
    connect-timeout: 1000
    host: 192.168.0.232

  kafka:
    bootstrap-servers: 192.168.0.232:9092
    consumer:
      group-id: 24
      auto-offset-reset: earliest
  mvc:
    path match:
      matching-strategy: ant_path_matcher

jwt:
  secret: 3B58F8E1C44C3F1750D5F0BAF2158AC1BC1C3C8B47FDE4A42669F16C871D19E7
  accessTokenExpirationMs: 8640000
  refreshTokenExpirationMs: 86400000

swagger:
  enable: true

